### ISSUE TITLE
Mission select page scrolling issue

### ISSUE THREAD

**Issue by seomk97** [Goranaws/Venture-Plan#1]
Hello,
I met an issue when I scroll down the mission selection page.

1. Before scrolling down
![image](https://user-images.githubusercontent.com/70502705/162586531-ad2d4ad8-6adb-4443-9af3-bcd25783b921.png)

2. After scrolling down
![image](https://user-images.githubusercontent.com/70502705/162586628-b3be3548-6483-43d1-9f47-791d0382bc31.png)

mission boxes go down and disappear.

Thanks for sharing great work!

**Comment by Goranaws** [comment]
I've just posted a possible fix. Please let me know what happens

**Comment by seomk97** [comment]
It's working now.

Thank you!

**Comment by Goranaws** [comment]
Awesome! If you don't mind me asking, do you like the adjustments I've made? I was not fond of the layout for the original mission buttons..

**Comment by seomk97** [comment]
It is perfect. thanks!
